/**
 * Make the generated data files byte-reproducible.
 *
 * THE PROBLEM
 * Hexo reads post source files in parallel, so each post's `tags` and
 * `categories` collections have no stable order between builds. The theme's own
 * templates were fixed with the `akari_sort_terms` helper, but
 * hexo-generator-feed and hexo-generator-searchdb iterate `post.tags` themselves
 * and emit whatever order they find.
 *
 * Measured: three consecutive `hexo clean && hexo generate` runs produced three
 * different `atom.xml` and three different `search.json`. The only differences
 * were the order of <category> elements inside a feed entry and the order of a
 * tag array inside a search entry — semantically identical, but it makes the
 * build non-reproducible and any output diffing useless.
 *
 * WHY NOT FIX THE DOCUMENTS
 * The obvious fix is to sort `post.tags` in a `before_generate` filter. That is
 * not possible: `tags` is defined on the document with a getter and no setter,
 * so assigning throws "Cannot set property tags of object which has only a
 * getter" (in strict mode; silently does nothing otherwise).
 *
 * WHAT THIS DOES
 * Rewrites the two files after they are generated but before Hexo flushes them
 * to disk — verified that `after_generate` runs at that point and that the route
 * data is still readable. `sitemap.xml` needs none of this: it is generated by
 * scripts/seo.js, which sorts its own entries.
 *
 * Deliberately FAIL-SOFT. This is a cosmetic normalisation; a mistake here must
 * never take down a deploy, so every step is guarded and a failure leaves the
 * original output untouched.
 */

'use strict';

/** Read a route's generated data as a string. Resolves null if unavailable. */
function readRoute(path) {
  return new Promise((resolve) => {
    let stream;
    try {
      stream = hexo.route.get(path);
    } catch (err) {
      return resolve(null);
    }
    if (!stream) return resolve(null);

    let data = '';
    stream.on('data', (chunk) => { data += chunk; });
    stream.on('end', () => resolve(data));
    stream.on('error', () => resolve(null));
  });
}

function byString(a, b) {
  if (a < b) return -1;
  if (a > b) return 1;
  return 0;
}

/** Sort the members of an object's array-valued keys, so JSON output is stable. */
function normaliseJson(text) {
  const parsed = JSON.parse(text);

  const sortEntry = (entry) => {
    if (!entry || typeof entry !== 'object') return entry;
    if (Array.isArray(entry.tags)) entry.tags = entry.tags.slice().sort(byString);
    if (Array.isArray(entry.categories)) entry.categories = entry.categories.slice().sort(byString);
    return entry;
  };

  if (Array.isArray(parsed)) {
    parsed.forEach(sortEntry);
    // The entry order itself comes from an unordered post list.
    parsed.sort((a, b) => byString(String(a && a.url || ''), String(b && b.url || '')));
    return JSON.stringify(parsed);
  }

  return JSON.stringify(parsed);
}

/**
 * Sort runs of consecutive `<category .../>` lines.
 *
 * The feed emits an entry's categories as one contiguous block. Sorting only
 * within such runs leaves every other line — including whitespace and the
 * surrounding <entry> structure — exactly as generated, so this cannot reorder
 * or corrupt the document as a whole. This is intentionally a line-wise
 * operation rather than an XML parse.
 */
function normaliseFeed(text) {
  const lines = text.split('\n');
  const out = [];
  let run = [];

  const flush = () => {
    if (run.length) out.push(...run.slice().sort(byString));
    run = [];
  };

  for (const line of lines) {
    if (/^\s*<category\b/.test(line)) run.push(line);
    else { flush(); out.push(line); }
  }
  flush();

  return out.join('\n');
}

hexo.extend.filter.register('after_generate', function () {
  const targets = [
    { path: 'search.json', normalise: normaliseJson },
    { path: 'atom.xml', normalise: normaliseFeed },
  ];

  return Promise.all(
    targets.map((target) =>
      readRoute(target.path)
        .then((text) => {
          if (!text) return null;
          const normalised = target.normalise(text);
          if (normalised && normalised !== text) hexo.route.set(target.path, normalised);
          return null;
        })
        .catch(() => {
          // Leave the generated output exactly as it was.
          return null;
        })
    )
  ).then(() => undefined);
});
